--- 
- name: Install nvm
  shell: curl -o- https://raw.githubusercontent.com/creationix/nvm/v{{ nvm_version }}/install.sh | bash && source {{ home_directory }}/.bashrc
  args:
    creates: "{{ home_directory }}/.nvm"
    chdir: "{{ home_directory }}"
    executable: /bin/bash

- name: Install Node and Set Default
  shell: source ~/.nvm/nvm.sh && nvm install {{ node_version }} && nvm alias default {{ node_version }}
  args:
     executable: /bin/bash      